# Generated by Django 6.0.1 on 2026-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
