# Generated by Django 6.0.1 on 2026-03-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_product_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variations',
            new_name='variations',
        ),
    ]
